from datetime import datetime

from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.orm import relationship

# from sqlalchemy import Index

db = SQLAlchemy()


class CentroCustos(db.Model):
    __tablename__ = "centro_custos"
    id_centro_custos = db.Column(db.Text, primary_key=True)
    ref_centro_custos = db.Column(db.Text, nullable=False)
    desc_centro_custos = db.Column(db.Text, nullable=False)
    status_centro_custos = db.Column(db.String(16))
    data_cad_centro = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    lixeira = db.Column(db.String(16))
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    client_by_cc = db.relationship("Client_by_CC", back_populates="cost_center")
    conta_pagamento_by_cc = db.relationship(
        "ContaPagamento", back_populates="cost_center"
    )


class DespesasRecorrentes(db.Model):
    id_custo = db.Column(db.Text, primary_key=True)
    id_empresa = db.Column(db.Text, nullable=False)
    nome_conta = db.Column(db.Text, nullable=False)
    id_categoria = db.Column(db.Text)
    categoria_custo = db.Column(db.Text)
    id_banco = db.Column(db.Text)
    id_fornecedor = db.Column(db.Text)
    nome_fornecedor = db.Column(db.Text)
    vencimento_custo = db.Column(db.Text)
    valor_custo = db.Column(db.Text)
    observacoes_custo = db.Column(db.Text)
    id_centro_custos = db.Column(db.Text)
    status_custo = db.Column(db.Text)
    forma_pagamento = db.Column(db.Text)
    periodicidade = db.Column(db.Text)
    dia_semana_ocorrencia = db.Column(db.Text)
    dia_mes_ocorrencia = db.Column(db.Text)
    intervalo_dias_ocorrencia = db.Column(db.Text)
    data_inicio_ocorrencia = db.Column(db.DateTime, default=datetime.utcnow)
    data_fim_ocorrencia = db.Column(db.DateTime, default=datetime.utcnow)
    data_cad_custo = db.Column(db.DateTime, default=datetime.utcnow)
    lixeira = db.Column(db.String(16))


class Pedido(db.Model):
    __tablename__ = "pedido"
    id_ped = db.Column(db.Text, primary_key=True)
    id_pedido = db.Column(db.Text, nullable=False)
    id_cliente = db.Column(db.Text, nullable=False)
    nome_cliente = db.Column(db.Text)
    cc = db.Column(db.Text)
    id_cc = db.Column(db.Text, db.ForeignKey("client_by_cc.CC"))
    vendedor_pedido = db.Column(db.Text)
    valor_total_produtos = db.Column(db.Float)
    desconto_pedido = db.Column(db.Float)
    desconto_pedido_porc = db.Column(db.Float)
    peso_total_nota = db.Column(db.Float)
    peso_total_nota_liq = db.Column(db.Float)
    frete_pedido = db.Column(db.Float)
    valor_total_nota = db.Column(db.Float)
    valor_baseICMS = db.Column(db.Float)
    valor_ICMS = db.Column(db.Float)
    valor_baseST = db.Column(db.Float)
    valor_ST = db.Column(db.Float)
    valor_IPI = db.Column(db.Float)

    condicao_pagamento = db.Column(db.Text)
    frete_por_pedido = db.Column(db.Integer)
    data_pedido = db.Column(db.DateTime)
    prazo_entrega = db.Column(db.Text)
    referencia_pedido = db.Column(db.Text)
    obs_pedido = db.Column(db.Text)
    obs_interno_pedido = db.Column(db.Text)
    status_pedido = db.Column(db.Text)
    contas_pedido = db.Column(db.Integer)
    data_cad_pedido = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    data_mod_pedido = db.Column(db.DateTime)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    lixeira = db.Column(db.String(8))
    client_by_cc_ref = db.relationship("Client_by_CC", back_populates="pedido_ref")


class Extrato(db.Model):
    __tablename__ = "extrato"
    id_local = db.Column(db.Integer, primary_key=True)
    id_fluxo = db.Column(db.Integer, nullable=False, unique=True)
    id_banco = db.Column(db.Integer, db.ForeignKey("banks.id_banco_cad"))
    nome_conta = db.Column(db.Text)
    id_cliente = db.Column(db.Integer)
    nome_cliente = db.Column(db.Text)
    data_fluxo = db.Column(db.Date)
    valor_fluxo = db.Column(db.Float)
    observacoes_fluxo = db.Column(db.Text)
    id_centro_custos = db.Column(db.Text)
    centro_custos_fluxo = db.Column(db.Text)
    id_categoria = db.Column(db.Integer)
    categoria_fluxo = db.Column(db.Text)
    forma_pagamento = db.Column(db.Text)
    tipo_fluxo = db.Column(db.Text)
    data_cad_fluxo = db.Column(db.DateTime)
    data_mod_fluxo = db.Column(db.DateTime)
    lixeira = db.Column(db.Text)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    bank = db.relationship("Banks", back_populates="extract_entries")


class ContaPagamento(db.Model):
    __tablename__ = "conta_pagamento"
    id_conta_pag = db.Column(db.Text, primary_key=True)
    id_registro = db.Column(db.Integer)
    nome_conta = db.Column(db.Text)
    id_categoria = db.Column(db.Integer)
    categoria_pag = db.Column(db.Text)
    id_banco = db.Column(db.Integer)
    id_fornecedor = db.Column(db.Integer)
    nome_fornecedor = db.Column(db.Text)
    vencimento_pag = db.Column(db.String(50))
    valor_pag = db.Column(db.Float)
    valor_pago = db.Column(db.Float)
    data_emissao = db.Column(db.DateTime)
    n_documento_pag = db.Column(db.Text)
    observacoes_pag = db.Column(db.Text)
    id_centro_custos = db.Column(
        db.Text, db.ForeignKey("centro_custos.id_centro_custos")
    )
    centro_custos_pag = db.Column(db.Text)
    liquidado_pag = db.Column(db.String(16))
    data_pagamento = db.Column(db.DateTime)
    obs_pagamento = db.Column(db.Text)
    forma_pagamento = db.Column(db.Text)
    valor_juros = db.Column(db.Float)
    valor_desconto = db.Column(db.Float)
    valor_acrescimo = db.Column(db.Float)
    data_cad_pag = db.Column(db.DateTime)
    data_mod_pag = db.Column(db.DateTime)
    agrupado = db.Column(db.String(8))
    agrupado_data = db.Column(db.DateTime)
    agrupado_user = db.Column(db.Text)
    agrupamento = db.Column(db.Text)
    lixeira = db.Column(db.String(16))
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    cost_center = db.relationship(
        "CentroCustos", back_populates="conta_pagamento_by_cc"
    )


class ContaReceber(db.Model):
    __tablename__ = "conta_receber"
    id_conta_rec = db.Column(db.Text, primary_key=True)
    id_registro = db.Column(db.Integer)
    nome_conta = db.Column(db.Text)
    id_categoria = db.Column(db.Integer)
    categoria_rec = db.Column(db.Text)
    id_banco = db.Column(db.Integer)
    id_cliente = db.Column(db.Integer)
    nome_cliente = db.Column(db.Text)
    vencimento_rec = db.Column(db.DateTime)
    valor_rec = db.Column(db.Text)
    valor_pago = db.Column(db.Text)
    data_emissao = db.Column(db.DateTime)
    n_documento_rec = db.Column(db.Text)
    observacoes_rec = db.Column(db.Text)
    id_centro_custos = db.Column(db.Integer)
    centro_custos_rec = db.Column(db.Text)
    liquidado_rec = db.Column(db.Text)
    data_pagamento = db.Column(db.DateTime)
    obs_pagamento = db.Column(db.Text)
    forma_pagamento = db.Column(db.Text)
    valor_juros = db.Column(db.Float)
    valor_desconto = db.Column(db.Float)
    valor_acrescimo = db.Column(db.Float)
    tipo_conta = db.Column(db.Text)
    data_cad_rec = db.Column(db.DateTime)
    data_mod_rec = db.Column(db.DateTime)
    agrupado = db.Column(db.Text)
    agrupado_data = db.Column(db.DateTime)
    agrupado_user = db.Column(db.Text)
    agrupamento = db.Column(db.Text)
    lixeira = db.Column(db.Text)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class ServiceOrder(db.Model):
    __tablename__ = "service_order"
    id_ordem = db.Column(db.Text, unique=True, primary_key=True)
    id_pedido = db.Column(db.Text)
    id_cliente = db.Column(db.Text)
    nome_cliente = db.Column(db.Text)
    referencia_ordem = db.Column(db.Text)
    tipo_servico = db.Column(db.Text)
    valor_total_servicos = db.Column(db.Float)
    valor_total_pecas = db.Column(db.Float)
    valor_total_despesas = db.Column(db.Float)
    valor_total_desconto = db.Column(db.Float)
    valor_total_os = db.Column(db.Float)
    condicao_pagamento_id = db.Column(db.Integer)
    condicao_pagamento = db.Column(db.Text)
    status_pedido = db.Column(db.Text)
    nota_servico_emitida = db.Column(db.Integer)
    obs_pedido = db.Column(db.Text)
    obs_interno_pedido = db.Column(db.Text)
    id_centro_custos = db.Column(db.Text, db.ForeignKey("client_by_cc.CC"))
    ref_centro_custos = db.Column(db.Text, nullable=False)
    data_pedido = db.Column(db.DateTime)
    data_cad_pedido = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    data_mod_pedido = db.Column(db.DateTime)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    lixeira = db.Column(db.String(64))
    client_by_cc_ref = db.relationship(
        "Client_by_CC", back_populates="service_order_ref"
    )


class Client(db.Model):
    __tablename__ = "client"
    id_cliente = db.Column(db.Text, primary_key=True)
    id_registro = db.Column(db.Integer)
    tipo_cadastro = db.Column(db.String(50))
    cnpj_cliente = db.Column(db.String(20))
    razao_cliente = db.Column(db.String(255))
    fantasia_cliente = db.Column(db.String(255))
    endereco_cliente = db.Column(db.String(255))
    numero_cliente = db.Column(db.String(20))
    bairro_cliente = db.Column(db.String(100))
    complemento_cliente = db.Column(db.String(100))
    referencia_cliente = db.Column(db.String(100))
    cep_cliente = db.Column(db.String(10))
    cep_cliente = db.Column(db.String(10))
    cidade_cliente = db.Column(db.String(100))
    lixeira = db.Column(db.String(10))
    uf_cliente = db.Column(db.String(2))
    tel_destinatario_cliente = db.Column(db.String(20))
    doc_destinatario_cliente = db.Column(db.String(20))
    nome_destinatario_cliente = db.Column(db.String(255))
    email_cliente = db.Column(db.String(255))
    data_cad_cliente = db.Column(db.String(20))
    data_mod_cliente = db.Column(db.String(20))
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    client_by_cc_ref = db.relationship("Client_by_CC", back_populates="client_ref")


class Clock_User(db.Model):
    __tablename__ = "clock_user"
    id = db.Column(db.String(255), primary_key=True)
    email = db.Column(db.String(255), nullable=False)
    name = db.Column(db.String(255), nullable=False)
    profile_pic = db.Column(db.String(255))
    active_workspace = db.Column(db.String(255))
    default_workspace = db.Column(db.String(255))
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    clock_time_entries = db.relationship("Clock_Time_Entry", back_populates="user")


class Clock_Client(db.Model):
    __tablename__ = "clock_client"
    id = db.Column(db.String(255), nullable=False, unique=True, primary_key=True)
    name = db.Column(db.String(255), nullable=False)
    note = db.Column(db.Text)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class Clock_Project(db.Model):
    __tablename__ = "clock_project"
    id = db.Column(db.String(255), primary_key=True)
    name = db.Column(db.String(255), nullable=False)
    client_id = db.Column(db.String(255), nullable=False)
    client_name = db.Column(db.String(255), nullable=False)
    cc_reference = db.Column(db.String(255), nullable=False)
    duration = db.Column(db.String(255), nullable=False)
    duration_minutes = db.Column(db.Integer, nullable=False)
    note = db.Column(db.Text)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    clock_time_entries = db.relationship("Clock_Time_Entry", back_populates="project")


class Clock_tag(db.Model):
    __tablename__ = "clock_tag"
    id = db.Column(db.String(255), primary_key=True)
    name = db.Column(db.String(512))  # Assuming date is stored as string
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    clock_time_entries = db.relationship("Clock_Time_Entry", back_populates="tag")


class Clock_Time_Entry(db.Model):
    __tablename__ = "clock_time_entry"
    id = db.Column(db.String(255), primary_key=True)
    description = db.Column(db.Text)
    user_id = db.Column(db.String(255), db.ForeignKey("clock_user.id"), nullable=False)
    project_id = db.Column(
        db.String(255), db.ForeignKey("clock_project.id"), nullable=False
    )
    tags_id = db.Column(db.Text, db.ForeignKey("clock_tag.id"), nullable=False)
    interval_start_moment = db.Column(
        db.DateTime, nullable=False, default=datetime.utcnow
    )
    interval_end_moment = db.Column(
        db.DateTime, nullable=False, default=datetime.utcnow
    )
    interval_duration = db.Column(db.String(255))
    interval_duration_minutes = db.Column(db.Integer, nullable=False)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    project = db.relationship("Clock_Project", back_populates="clock_time_entries")
    user = db.relationship("Clock_User", back_populates="clock_time_entries")
    tag = db.relationship("Clock_tag", back_populates="clock_time_entries")


class PrimaData(db.Model):
    __tablename__ = "prima_data"
    id_local = db.Column(db.Integer, primary_key=True)
    ID = db.Column(db.String(255), nullable=False, unique=True)
    CENTRO_DE_CUSTO = db.Column(db.Text)
    PROJETO = db.Column(db.Text)
    CLIENTE = db.Column(db.Text)
    DESCRICAO = db.Column(db.Text)
    TAREFA = db.Column(db.Text)
    USUARIO = db.Column(db.Text)
    ATIVIDADE = db.Column(db.Text)
    DATA_INICIO = db.Column(db.String(255), nullable=False)
    HORA_INICIO = db.Column(db.String(255), nullable=False)
    DATA_FINAL = db.Column(db.String(255), nullable=False)
    HORA_FINAL = db.Column(db.String(255), nullable=False)
    interval_start_moment = db.Column(
        db.DateTime, nullable=False, default=datetime.utcnow
    )
    interval_end_moment = db.Column(
        db.DateTime, nullable=False, default=datetime.utcnow
    )
    time_difference_in_minutes = db.Column(db.Integer)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class Contexted_hour_entry(db.Model):
    __tablename__ = "contexted_hour_entry"
    CC_LABEL = db.Column(db.Text)
    CC_REF_ID = db.Column(db.Text, db.ForeignKey("client_by_cc.CC"))
    PROJETO = db.Column(db.Text)
    CLIENTE = db.Column(db.Text)
    DESCRICAO = db.Column(db.Text)
    USUARIO = db.Column(db.Text)
    GRUPO = db.Column(db.Text)
    ATIVIDADE = db.Column(db.Text)
    DATA_INICIO = db.Column(db.String(32))
    HORA_INICIO = db.Column(db.String(32))
    DATA_FINAL = db.Column(db.String(32))
    HORA_FINAL = db.Column(db.String(32))
    HORAS_MINUTOS = db.Column(db.Float)
    HH = db.Column(db.Float)
    ANO = db.Column(db.Integer)
    FATOR_ANO = db.Column(db.Integer)
    ORIGEM = db.Column(db.Text)
    ORIGEM_ID = db.Column(db.Text, unique=True)
    SEED = db.Column(db.Text, unique=True)
    TOKEN = db.Column(db.Text, primary_key=True, unique=True)
    CARGO = db.Column(db.Text)
    interval_start_moment = db.Column(
        db.DateTime, nullable=False, default=datetime.utcnow
    )
    interval_end_moment = db.Column(
        db.DateTime, nullable=False, default=datetime.utcnow
    )
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    client_by_cc_ref = db.relationship(
        "Client_by_CC", back_populates="contexted_hour_ref"
    )


class Relatorio_CC(db.Model):
    ID = db.Column(db.String(255), primary_key=True, unique=True)
    ID_SEED = db.Column(db.String(512))
    ID_CC = db.Column(db.String(255))
    CC = db.Column(db.String(255))
    CC_LABEL = db.Column(db.String(255))
    VENCIMENTO = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    FORNECEDOR = db.Column(db.String(255))
    NOME_DESPESA = db.Column(db.String(255))
    SITUACAO = db.Column(db.String(255))
    DATA_PAGAMENTO = db.Column(db.DateTime, default=datetime.utcnow)
    CATEGORIA = db.Column(db.String(255))
    VALOR = db.Column(db.Float)
    TYPE = db.Column(db.String(32))  # Assuming date is stored as string
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


# class CC_REPORT(db.Model):
#     ID = db.Column(db.String(255), primary_key=True, unique=True)
#     ID_SEED = db.Column(db.String(512))
#     ID_CC = db.Column(db.String(255))
#     CC = db.Column(db.String(255))
#     CC_LABEL = db.Column(db.String(255))
#     VENCIMENTO = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
#     FORNECEDOR = db.Column(db.String(255))
#     NOME_DESPESA = db.Column(db.String(255))
#     SITUACAO = db.Column(db.String(255))
#     DATA_PAGAMENTO = db.Column(db.DateTime, default=datetime.utcnow)
#     CATEGORIA = db.Column(db.String(255))
#     VALOR = db.Column(db.Float)
#     TYPE = db.Column(db.String(32))  # Assuming date is stored as string
#     created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
#     updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class Client_by_CC(db.Model):
    __tablename__ = "client_by_cc"
    CC = db.Column(db.Text, primary_key=True)
    id_cc = db.Column(db.Text, db.ForeignKey("centro_custos.id_centro_custos"))
    id_cliente = db.Column(db.Text, db.ForeignKey("client.id_cliente"))
    ref_cc = db.Column(db.Text)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    cost_center = db.relationship("CentroCustos", back_populates="client_by_cc")
    client_ref = db.relationship("Client", back_populates="client_by_cc_ref")
    contexted_hour_ref = db.relationship(
        "Contexted_hour_entry", back_populates="client_by_cc_ref"
    )
    service_order_ref = db.relationship(
        "ServiceOrder", back_populates="client_by_cc_ref"
    )
    pedido_ref = db.relationship("Pedido", back_populates="client_by_cc_ref")


class Buy_order(db.Model):
    __tablename__ = "buy_order"
    id_local = db.Column(db.Integer, primary_key=True)
    id_ordem = db.Column(db.Integer, nullable=False, unique=True)
    id_pedido = db.Column(db.Integer, nullable=False)
    id_cliente = db.Column(db.Integer, nullable=False)
    nome_cliente = db.Column(db.Text)
    vendedor_pedido = db.Column(db.Text)
    valor_total_produtos = db.Column(db.Float)
    desconto_pedido = db.Column(db.Float)
    peso_total_nota = db.Column(db.Float)
    frete_pedido = db.Column(db.Float)
    valor_total_nota = db.Column(db.Float)
    valor_baseICMS = db.Column(db.Float)
    valor_ICMS = db.Column(db.Float)
    valor_baseST = db.Column(db.Float)
    valor_ST = db.Column(db.Float)
    valor_IPI = db.Column(db.Float)
    condicao_pagamento_id = db.Column(db.Integer)
    condicao_pagamento = db.Column(db.Integer)
    transportadora_pedido = db.Column(db.Text)
    id_transportadora = db.Column(db.Integer)
    data_pedido = db.Column(db.Text)
    prazo_entrega = db.Column(db.Text)
    obs_pedido = db.Column(db.Text)
    obs_interno_pedido = db.Column(db.Text)
    status_pedido = db.Column(db.Text)
    contas_pedido = db.Column(db.Integer)
    estoque_pedido = db.Column(db.Integer)
    entrada_emitida = db.Column(db.Integer)
    usuario_cad_pedido = db.Column(db.Integer)
    usuario_mod_pedido = db.Column(db.Integer)
    data_cad_pedido = db.Column(db.DateTime)
    data_mod_pedido = db.Column(db.DateTime)
    lixeira = db.Column(db.Text)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class User_by_name(db.Model):
    id_local = db.Column(db.Integer, primary_key=True)
    user = db.Column(db.String(512), unique=True)
    user_name = db.Column(db.String(512))
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class Valor_base_by_cargo(db.Model):
    id_local = db.Column(db.Integer, primary_key=True)
    cargo = db.Column(db.String(512), unique=True)
    valor_base = db.Column(db.Float)
    descricao_cargo = db.Column(db.Text)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class Valor_base_by_employer(db.Model):
    id_matricula = db.Column(db.Integer, primary_key=True)
    employer = db.Column(db.String(512), unique=True)
    valor_base = db.Column(db.Float)
    adm_percent = db.Column(db.Float)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class Categoria_financeira(db.Model):
    id_categoria = db.Column(db.Integer, primary_key=True)
    tipo_categoria = db.Column(db.Text)
    desc_categoria = db.Column(db.Text)
    lixeira = db.Column(db.Text)
    visivel_dre = db.Column(db.Text)
    grupo_financeiro = db.Column(db.Text)
    categoria_pai = db.Column(db.Text)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class Colaborador_cargo_value(db.Model):
    id_local = db.Column(db.Integer, primary_key=True)
    colaborador = db.Column(db.String(512))
    ativo = db.Column(db.Integer)
    cargo_id = db.Column(db.Integer)
    adm_percent = db.Column(db.Float)
    momento_inicio_cargo = db.Column(
        db.DateTime, nullable=False, default=datetime.utcnow
    )
    momento_fim_cargo = db.Column(db.DateTime, default=datetime.utcnow)
    cargo_atual = db.Column(db.Integer)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class Update_route_status(db.Model):
    route = db.Column(db.String(512), primary_key=True)
    runned = db.Column(db.Integer)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    start = db.Column(db.DateTime, default=datetime.utcnow)
    end = db.Column(db.DateTime, default=datetime.utcnow)
    active = db.Column(db.Boolean, default=True)
    route_name = db.Column(db.Text)
    logs_count = db.Column(db.Integer)
    error_count = db.Column(db.Integer)


class Update_cc_report_status(db.Model):
    cc_id = db.Column(db.String(512), primary_key=True)
    entries_runned = db.Column(db.Integer)
    outputs_runned = db.Column(db.Integer)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class Banks(db.Model):
    __tablename__ = "banks"
    id_banco_cad = db.Column(db.Integer, primary_key=True)
    nome_banco_cad = db.Column(db.String(512))
    saldo_inicial = db.Column(db.Float)
    saldo_inicial_data = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    id_carteira = db.Column(db.Integer)
    carteira_banco = db.Column(db.Integer)
    convenio_banco = db.Column(db.Integer)
    cedente_banco = db.Column(db.Integer)
    agencia_banco = db.Column(db.Integer)
    conta_banco = db.Column(db.Integer)
    codigo_cedente = db.Column(db.Integer)
    status_banco = db.Column(db.String(10))
    com_registro = db.Column(db.Integer)
    data_cad_banco = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    data_mod_banco = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    lixeira = db.Column(db.String(10))
    numero_banco = db.Column(db.String(10))
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    extract_entries = db.relationship("Extrato", back_populates="bank")


class Indice_ano(db.Model):
    __tablename__ = "indice_ano"
    id_ano = db.Column(db.Integer, primary_key=True)
    indice = db.Column(db.Float)
    imposto_servico = db.Column(db.Float)
    imposto_material = db.Column(db.Float)
    margem_contribuicao = db.Column(db.Float)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class OrdersManage(db.Model):
    __tablename__ = "orders_manage"
    ID = db.Column(db.Text, primary_key=True)
    type = db.Column(db.Text)
    id_origem = db.Column(db.Text)
    id_pedido = db.Column(db.Text)
    id_cliente = db.Column(db.Text)
    ref_cc = db.Column(db.Text)
    id_cc_by_client = db.Column(db.Text)
    nome_cliente = db.Column(db.Text)
    ref_date = db.Column(db.DateTime)
    vendedor_pedido = db.Column(db.Text)
    valor_total_produtos = db.Column(db.Float)
    desconto_pedido = db.Column(db.Float)
    desconto_pedido_porc = db.Column(db.Float)
    peso_total_nota = db.Column(db.Float)
    peso_total_nota_liq = db.Column(db.Float)
    frete_pedido = db.Column(db.Float)
    referencia_ordem = db.Column(db.Text)
    valor_baseICMS = db.Column(db.Float)
    valor_ICMS = db.Column(db.Float)
    valor_baseST = db.Column(db.Float)
    valor_ST = db.Column(db.Float)
    valor_IPI = db.Column(db.Float)
    condicao_pagamento_id = db.Column(db.Float)
    valor_total_servicos = db.Column(db.Float)
    valor_total_pecas = db.Column(db.Float)
    valor_total_despesas = db.Column(db.Float)
    valor_total_desconto = db.Column(db.Float)
    valor_total_os = db.Column(db.Float)
    frete_por_pedido = db.Column(db.Float)
    data_pedido = db.Column(db.DateTime)
    prazo_entrega = db.Column(db.Text)
    referencia_pedido = db.Column(db.Text)
    obs_pedido = db.Column(db.Text)
    obs_interno_pedido = db.Column(db.Text)
    status_pedido = db.Column(db.Text)
    data_cad_pedido = db.Column(db.DateTime)
    data_mod_pedido = db.Column(db.DateTime)
    condicao_pagamento = db.Column(db.Integer)
    valor_total_nota = db.Column(db.Float)
    nota_servico_emitida = db.Column(db.Integer)
    lixeira = db.Column(db.Text)
    contas_pedido = db.Column(db.Text)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class Employers(db.Model):
    __tablename__ = "employers"
    vhsys_id = db.Column(db.Integer, primary_key=True)
    matricula = db.Column(db.Integer)
    nome = db.Column(db.Text)
    cargo = db.Column(db.Text)
    cbo = db.Column(db.Text)
    rg = db.Column(db.Text)
    cpf = db.Column(db.Text)
    data_nascimento = db.Column(db.DateTime)
    salario = db.Column(db.Float)
    data_adm = db.Column(db.DateTime)
    data_dem = db.Column(db.DateTime)
    status = db.Column(db.Text)
    data_cad = db.Column(db.DateTime)
    data_mod = db.Column(db.DateTime)
    depto = db.Column(db.Text)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class EmployersData(db.Model):
    __tablename__ = "employersData"
    id_funcionario = db.Column(db.Text, primary_key=True)
    nome_funcionario = db.Column(db.Text)
    rg_funcionario = db.Column(db.Text)
    cpf_funcionario = db.Column(db.Text)
    matricula_funcionario = db.Column(db.Text)
    sexo_funcionario = db.Column(db.Text)
    local_nascimento_funcionario = db.Column(db.Text)
    orgao_emissor_rg = db.Column(db.Text)
    serie_ctps_funcionario = db.Column(db.Text)
    cep_funcionario = db.Column(db.Text)
    endereco_funcionario = db.Column(db.Text)
    numero_funcionario = db.Column(db.Text)
    bairro_funcionario = db.Column(db.Text)
    cidade_funcionario = db.Column(db.Text)
    uf_funcionario = db.Column(db.Text)
    complemento_funcionario = db.Column(db.Text)
    celular_funcionario = db.Column(db.Text)
    fone_funcionario = db.Column(db.Text)
    email_funcionario = db.Column(db.Text)
    nome_pai_funcionario = db.Column(db.Text)
    nome_mae_funcionario = db.Column(db.Text)
    observacoes_funcionario = db.Column(db.Text)
    pis_funcionario = db.Column(db.Text)
    ctps_funcionario = db.Column(db.Text)
    uf_ctps_funcionario = db.Column(db.Text)
    banco_funcionario = db.Column(db.Text)
    agencia_funcionario = db.Column(db.Text)
    conta_funcionario = db.Column(db.Text)
    cargo_funcionario = db.Column(db.Text)
    nome_cargo_funcionario = db.Column(db.Text)
    cbo_funcionario = db.Column(db.Text)
    departamento_funcionario = db.Column(db.Text)
    trabalho_inicio = db.Column(db.Text)
    trabalho_termino = db.Column(db.Text)
    intervalo_inicio = db.Column(db.Text)
    intervalo_termino = db.Column(db.Text)
    salario_funcionario = db.Column(db.Text)
    status_funcionario = db.Column(db.Text)
    data_admissao_funcionario = db.Column(db.DateTime)
    data_nascimento_funcionario = db.Column(db.DateTime)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class EmployersDataDependents(db.Model):
    __tablename__ = "employersDependents"
    dependents_id = db.Column(db.Text, primary_key=True)
    id_funcionario = db.Column(db.Text)
    nome_funcionario = db.Column(db.Text)
    nome_dependente = db.Column(db.Text)
    tipo_dependente = db.Column(db.Text)
    fone_dependente = db.Column(db.Text)
    rg = db.Column(db.Text)
    cpf = db.Column(db.Text)
    data_nascimento = db.Column(db.DateTime)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class EmployersDataBenefits(db.Model):
    __tablename__ = "employersBenefits"
    benefit_id = db.Column(db.Text, primary_key=True)
    id_funcionario = db.Column(db.Text, primary_key=True)
    nome_funcionario = db.Column(db.Text)
    nome = db.Column(db.Text)
    valor = db.Column(db.Float)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class EmployersDataPosition(db.Model):
    __tablename__ = "employersPosition"
    position_id = db.Column(db.Text, primary_key=True)
    positon_name = db.Column(db.Text)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class CostEntryByCC(db.Model):
    __tablename__ = "coustEntryByCC"
    coustEntryByCC_id = db.Column(db.Text, primary_key=True)
    value = db.Column(db.Float)
    user_email = db.Column(db.Text)
    register_photo_name = db.Column(db.Text)
    register_photo_link = db.Column(db.Text)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class SalesNFReport(db.Model):
    __tablename__ = "salesNFReport"
    ID = db.Column(db.Text)
    Nota = db.Column(db.Text , primary_key=True)
    Cliente = db.Column(db.Text)
    CNPJ = db.Column(db.Text)
    Endereco = db.Column(db.Text)
    Numero = db.Column(db.Text)
    Complemento = db.Column(db.Text)
    Bairro = db.Column(db.Text)
    Cidade = db.Column(db.Text)
    Estado = db.Column(db.Text)
    CEP = db.Column(db.Text)
    Email = db.Column(db.Text)
    Telefone = db.Column(db.Text)
    Vendedor = db.Column(db.Text)
    ValorProdutos = db.Column(db.Numeric(10, 2), default=0.00)
    ValorDesconto = db.Column(db.Numeric(10, 2), default=0.00)
    ValorFrete = db.Column(db.Text)
    ValorTotal = db.Column(db.Numeric(10, 2), default=0.00)
    TotalParcelas = db.Column(db.Text)
    TotalUnidades = db.Column(db.Text)
    ValorICMS = db.Column(db.Numeric(10, 2), default=0.00)
    ValorIPI = db.Column(db.Numeric(10, 2), default=0.00)
    ValorST = db.Column(db.Numeric(10, 2), default=0.00)
    PesoBruto = db.Column(db.Numeric(10, 2), default=0.00)
    PesoLiquido = db.Column(db.Numeric(10, 2), default=0.00)
    Transportadora = db.Column(db.Text)
    DataPedido = db.Column(db.Text)
    QtdeProdutos = db.Column(db.Text)
    CFOP = db.Column(db.Text)
    Natureza = db.Column(db.Text)
    Contas = db.Column(db.Text)
    Estoque = db.Column(db.Text)
    Comissao = db.Column(db.Text)
    Chave = db.Column(db.Text)
    Protocolo = db.Column(db.Text)
    DataEmissao = db.Column(db.Text)
    DataAutorizacao = db.Column(db.Text)
    Situacao = db.Column(db.Text)
    DataCad = db.Column(db.Text)
    DataMod = db.Column(db.Text)
    Observacoes = db.Column(db.Text)
    ObservacoesInternas = db.Column(db.Text)
    CategoriaFinanceira = db.Column(db.Text)
    Volumes = db.Column(db.Text)
    EmitidoPor = db.Column(db.Text)
    CanceladoPor = db.Column(db.Text)
    DataCancelamento = db.Column(db.Text)
    cc_ref = db.Column(db.Text)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class ServiceNFReport(db.Model):
    __tablename__ = "serviceNFReport"
    ID = db.Column(db.Text)
    RPS = db.Column(db.Text, primary_key=True)
    Nota = db.Column(db.Text)
    Cliente = db.Column(db.Text)
    CNPJ = db.Column(db.Text)
    Endereco = db.Column(db.Text)
    Numero = db.Column(db.Text)
    Complemento = db.Column(db.Text)
    Bairro = db.Column(db.Text)
    Cidade = db.Column(db.Text)
    Estado = db.Column(db.Text)
    CEP = db.Column(db.Text)
    Email = db.Column(db.Text)
    Telefone = db.Column(db.Text)
    Vendedor = db.Column(db.Text)
    ValorServicos = db.Column(db.Numeric(10, 2), default=0.00)
    ValorTotal = db.Column(db.Numeric(10, 2), default=0.00)
    TotalParcelas = db.Column(db.Text)
    ValorDeducoes = db.Column(db.Text)
    Aliquota = db.Column(db.Text)
    ValorISS = db.Column(db.Numeric(10, 2), default=0.00)
    ISSRetido = db.Column(db.Text)
    ValorCOFINS = db.Column(db.Numeric(10, 2), default=0.00)
    ValorPIS = db.Column(db.Numeric(10, 2), default=0.00)
    ValorCSLL = db.Column(db.Numeric(10, 2), default=0.00)
    ValorIR = db.Column(db.Numeric(10, 2), default=0.00)
    ValorINSS = db.Column(db.Numeric(10, 2), default=0.00)
    ValorTributos = db.Column(db.Numeric(10, 2), default=0.00)
    DataPedido = db.Column(db.Text)
    LocalPrestacao = db.Column(db.Text)
    Contas = db.Column(db.Text)
    Chave = db.Column(db.Text)
    Protocolo = db.Column(db.Text)
    Descricao = db.Column(db.Text)
    DataEmissao = db.Column(db.Text)
    Situacao = db.Column(db.Text)
    DataCad = db.Column(db.Text)
    DataMod = db.Column(db.Text)
    cc_ref = db.Column(db.Text)
    ObservacoesInternas = db.Column(db.Text)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class TangerinoEntries(db.Model):
    __tablename__ = "TangerinoEntries"
    ID = db.Column(db.Text, primary_key=True)
    DAY = db.Column(db.Text)
    USER_ID = db.Column(db.Text)
    EMPLOYER = db.Column(db.Text)
    EMPLOYER_CPF = db.Column(db.Text)
    HORAS_TRABALHADAS = db.Column(db.Text)
    HORAS_TRABALHADAS_MINUTES = db.Column(db.Integer)
    HORAS_PREVISTAS = db.Column(db.Text)
    HORAS_PREVISTAS_MINUTES = db.Column(db.Integer)
    TURN_01_START = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    TURN_01_END = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    TURN_02_START = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    TURN_02_END = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    TURN_03_START = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    TURN_03_END = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    TURN_04_START = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    TURN_04_END = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    last_run = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class Update_extension_services(db.Model):
    ACTION = db.Column(db.Text, primary_key=True)
    RUN_AFTER = db.Column(db.Integer, default=720)
    RUN_STATUS = db.Column(db.Integer, default=0)
    PROGRESS_VALUE = db.Column(db.Integer, default=0)
    LAST_RUN = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    LAST_UPDATE = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    SOURCE = db.Column(db.Text)
    STATUS_MESSAGE = db.Column(db.Text)


class NF_ServiceMetadata(db.Model):
    codigo = db.Column(db.Text, primary_key=True)
    contas = db.Column(db.Text)
    boletos = db.Column(db.Text)
    nota = db.Column(db.Text)
    cliente = db.Column(db.Text)
    status = db.Column(db.Text)
    vendedor = db.Column(db.Text)
    chave = db.Column(db.Text)
    numeronfs = db.Column(db.Text)
    notarecibo = db.Column(db.Text)
    vinculooscomnfs = db.Column(db.Text)
    runned = db.Column(db.Integer, default=0)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class NF_Service(db.Model):
    id_servico = db.Column(db.Text, primary_key=True)
    obs_interno_pedido = db.Column(db.Text)
    obs_pedido = db.Column(db.Text)
    numero_processo = db.Column(db.Text)
    condicao_pagamento = db.Column(db.Text)
    condicao_pagamento_id = db.Column(db.Text)
    valor_iss = db.Column(db.Text)
    aliq_iss = db.Column(db.Text)
    valor_ir = db.Column(db.Text)
    aliq_ir = db.Column(db.Text)
    valor_contribuicao = db.Column(db.Text)
    aliq_contribuicao = db.Column(db.Text)
    valor_pis = db.Column(db.Text)
    aliq_pis = db.Column(db.Text)
    valor_cofins = db.Column(db.Text)
    aliq_cofins = db.Column(db.Text)
    valor_material = db.Column(db.Text)
    valor_tributos_mun = db.Column(db.Text)
    valor_aliq_tributos_mun = db.Column(db.Text)
    valor_tributos = db.Column(db.Text)
    valor_aliq_tributos = db.Column(db.Text)
    valor_imposto = db.Column(db.Text)
    valor_aliquota = db.Column(db.Text)
    valor_base_calculo = db.Column(db.Text)
    valor_condicionado = db.Column(db.Text)
    valor_incondicionado = db.Column(db.Text)
    valor_deducoes = db.Column(db.Text)
    itemLista_servico = db.Column(db.Text)
    valor_total_nota = db.Column(db.Text)
    valor_total_servicos = db.Column(db.Text)
    desc_servicos = db.Column(db.Text)
    serie_nota = db.Column(db.Text)
    id_pedido = db.Column(db.Text)
    vendedor_pedido_id = db.Column(db.Text)
    vendedor_pedido = db.Column(db.Text)
    ultrapassar_limite_credito = db.Column(db.Text)
    contas_pedido = db.Column(db.Text)
    id_cliente = db.Column(db.Text)
    nome_cliente = db.Column(db.Text)
    cc_ref = db.Column(db.Text)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class NF(db.Model):
    id_venda = db.Column(db.String(255), primary_key=True)
    tp_nfe = db.Column(db.String(255))
    serie_nota = db.Column(db.String(255))
    id_pedido = db.Column(db.String(255))
    id_cliente = db.Column(db.String(255))
    nome_cliente = db.Column(db.String(255))
    vendedor_pedido = db.Column(db.String(255))
    vendedor_pedido_id = db.String(255)
    valor_total_produtos = db.Column(db.Numeric(10, 2), default=0.00)
    desconto_pedido = db.Column(db.Numeric(10, 2), default=0.00)
    peso_total_nota = db.Column(db.Numeric(10, 4), default=0.0000)
    peso_total_nota_liq = db.Column(db.Numeric(10, 4), default=0.0000)
    frete_pedido = db.Column(db.Numeric(10, 2), default=0.00)
    valor_total_nota = db.Column(db.Numeric(10, 2), default=0.00)
    valor_baseICMS = db.Column(db.Numeric(10, 2), default=0.00)
    valor_ICMS = db.Column(db.Numeric(10, 2), default=0.00)
    valor_baseST = db.Column(db.Numeric(10, 2), default=0.00)
    valor_ST = db.Column(db.Numeric(10, 2), default=0.00)
    valor_IPI = db.Column(db.Numeric(10, 2), default=0.00)
    valor_despesas = db.Column(db.Numeric(10, 2), default=0.00)
    condicao_pagamento = db.Column(db.Text)
    transportadora_pedido = db.Column(db.String(255))
    id_transportadora = db.String(255)
    frete_por_pedido = db.Column(db.Text)
    volumes_transporta = db.Column(db.Text)
    especie_transporta = db.Column(db.String(100))
    marca_transporta = db.Column(db.String(100))
    numeracao_transporta = db.Column(db.String(50))
    placa_transporta = db.Column(db.String(10))
    uf_embarque = db.Column(db.String(2))
    local_embarque = db.Column(db.String(255))
    data_pedido = db.Column(db.Text)
    data_pedido_hora = db.Column(db.Time)
    data_emissao = db.Column(db.Text)
    natureza_pedido = db.Column(db.String(255))
    finalidade_nfe = db.Column(db.Text)
    obs_pedido = db.Column(db.Text)
    obs_interno_pedido = db.Column(db.Text)
    status_pedido = db.Column(db.String(50))
    contas_pedido = db.Column(db.Integer, default=0)
    comissao_pedido = db.Column(db.Numeric(10, 2), default=0.00)
    boletos_pedido = db.Column(db.Text)
    estoque_pedido = db.Column(db.Text)
    nota_emitida = db.Column(db.Text)
    nota_chave = db.Column(db.Text)
    nota_protocolo = db.Column(db.Text)
    nota_codigov = db.Column(db.Text)
    nota_recibo = db.Column(db.Text)
    nota_data_autorizacao = db.Column(db.Text)
    nota_usuario_autorizacao = db.Column(db.Text)
    nota_data_cancelamento = db.Column(db.Text)
    nota_usuario_cancelamento = db.Column(db.Text)
    nota_motivo_cancelamento = db.Column(db.Text)
    nota_denegada = db.Column(db.Text)
    nota_importada = db.Column(db.Text)
    nota_scan = db.Column(db.Text)
    data_cad_pedido = db.Column(db.Text)
    data_mod_pedido = db.Column(db.Text)
    ambiente = db.Column(db.Text)
    lixeira = db.Column(db.String(10), default="Nao")
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class Tangerino_entries(db.Model):
    ID = db.Column(db.Text, primary_key=True)
    DAY_REF = db.Column(db.Text)
    DAY = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    EMPLOYER = db.Column(db.Text)
    EMPLOYER_CPF = db.Column(db.Text)
    worked_hours = db.Column(db.Text)
    worked_hours_minutes = db.Column(db.Integer)
    work_expect = db.Column(db.Text)
    work_expect_minutes = db.Column(db.Integer)
    TURN_01_START = db.Column(db.DateTime, default=datetime.utcnow)
    TURN_01_END = db.Column(db.DateTime, default=datetime.utcnow)
    TURN_02_START = db.Column(db.DateTime, default=datetime.utcnow)
    TURN_02_END = db.Column(db.DateTime, default=datetime.utcnow)
    TURN_03_START = db.Column(db.DateTime, default=datetime.utcnow)
    TURN_03_END = db.Column(db.DateTime, default=datetime.utcnow)
    TURN_04_START = db.Column(db.DateTime, default=datetime.utcnow)
    TURN_04_END = db.Column(db.DateTime, default=datetime.utcnow)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow)


class Current_worked_hours(db.Model):
    ID = db.Column(db.Text, primary_key=True)
    description_CLOCK = db.Column(db.Text)
    interval_duration_minutes_CLOCK = db.Column(db.Numeric(10, 2))
    email_CLOCK = db.Column(db.Text)
    day_reference_CLOCK = db.Column(db.Text)
    EMPLOYER_TANGERINO = db.Column(db.Text)
    worked_hours_minutes_TANGERINO = db.Column(db.Numeric(10, 2))
    work_expect_minutes_TANGERINO = db.Column(db.Numeric(10, 2))
    DAY_REF_TANGERINO = db.Column(db.Text)
    token = db.Column(db.Text)
    DAY = db.Column(db.DateTime, default=datetime.utcnow)
    valid_clock = db.Column(db.Boolean)
    valid_tangerino = db.Column(db.Boolean)
    worked_minus_expected_minutes = db.Column(db.Numeric(10, 2))
    status = db.Column(db.Text)
    worked_hours_hhmm = db.Column(db.Text)
    expected_hours_hhmm = db.Column(db.Text)


class Merch_entry(db.Model):
    __tablename__ = "merch_entry"
    id_entrada = db.Column(db.Text, primary_key=True)
    id_pedido = db.Column(db.Text)
    id_cliente = db.Column(db.Text)
    nome_cliente = db.Column(db.Text)
    vendedor_pedido = db.Column(db.Text, nullable=True)
    valor_total_produtos = db.Column(db.Float)
    desconto_pedido = db.Column(db.Float)
    peso_total_nota = db.Column(db.Float)
    frete_pedido = db.Column(db.Float)
    valor_total_nota = db.Column(db.Float)
    valor_baseICMS = db.Column(db.Float)
    valor_ICMS = db.Column(db.Float)
    valor_baseST = db.Column(db.Float)
    valor_ST = db.Column(db.Float)
    valor_IPI = db.Column(db.Float)
    valor_PIS = db.Column(db.Float)
    valor_COFINS = db.Column(db.Float)
    condicao_pagamento = db.Column(db.Integer)
    transportadora_pedido = db.Column(db.Text)
    id_transportadora = db.Column(db.Text)
    data_pedido = db.Column(db.DateTime)
    id_centro_custos = db.Column(db.Integer)
    centro_custos_pedido = db.Column(db.Text, nullable=True)
    obs_pedido = db.Column(db.Text)
    obs_interno_pedido = db.Column(db.Text, nullable=True)
    status_pedido = db.Column(db.Text)
    contas_pedido = db.Column(db.Integer)
    estoque_pedido = db.Column(db.Integer)
    nota_numero = db.Column(db.Text)
    nota_chave = db.Column(db.Text)
    nota_protocolo = db.Column(db.Text)
    nota_data_autorizacao = db.Column(db.DateTime)
    data_cad_pedido = db.Column(db.DateTime, default=datetime.utcnow)
    data_mod_pedido = db.Column(db.DateTime, nullable=True)
    modelo_nota = db.Column(db.Text, nullable=True)
    serie_nota = db.Column(db.Text)
    importacao = db.Column(db.Text)
    almoxarifado = db.Column(db.Text)
    lixeira = db.Column(db.Text)
    usuario_cad_pedido = db.Column(db.Integer)
    usuario_mod_pedido = db.Column(db.Integer)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class Product_entry(db.Model):
    __tablename__ = "product_entry"
    id_ped_produto = db.Column(db.Text, primary_key=True)
    id_entrada = db.Column(db.Text)
    id_produto = db.Column(db.Text)
    id_almoxarifado = db.Column(db.Text)
    id_lote = db.Column(db.Text)
    desc_produto = db.Column(db.Text)
    qtde_produto = db.Column(db.Text)
    unidade_produto = db.Column(db.Text)
    desconto_produto = db.Column(db.Float)
    ipi_produto = db.Column(db.Float)
    icms_produto = db.Column(db.Float)
    cfop_produto = db.Column(db.Text)
    ncm_produto = db.Column(db.Float)
    valor_unit_produto = db.Column(db.Text)
    valor_total_produto = db.Column(db.Text)
    peso_produto = db.Column(db.Float)
    peso_liq_produto = db.Column(db.Float)
    json_localizacoes = db.Column(db.Text)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)




class Product(db.Model):
    __tablename__ = "products"
    id_produto = db.Column(db.Text, primary_key=True)
    id_registro = db.Column(db.Text)
    id_empresa = db.Column(db.Text)
    id_categoria = db.Column(db.Text)
    cod_produto = db.Column(db.Text)
    marca_produto = db.Column(db.Text)
    desc_produto = db.Column(db.Text)
    atalho_produto = db.Column(db.Text)
    fornecedor_produto = db.Column(db.Text)
    fornecedor_produto_id = db.Column(db.Text)
    produto_variado = db.Column(db.Text)
    id_produto_parent = db.Column(db.Text)
    minimo_produto = db.Column(db.Text)
    maximo_produto = db.Column(db.Text)
    estoque_produto = db.Column(db.Text)
    unidade_produto = db.Column(db.Text)
    valor_produto = db.Column(db.Text)
    valor_custo_produto = db.Column(db.Text)
    peso_produto = db.Column(db.Text)
    peso_liq_produto = db.Column(db.Text)
    icms_produto = db.Column(db.Text)
    ipi_produto = db.Column(db.Text)
    pis_produto = db.Column(db.Text)
    cofins_produto = db.Column(db.Text)
    unidade_tributavel = db.Column(db.Text)
    cest_produto = db.Column(db.Text)
    beneficio_fiscal = db.Column(db.Text)
    ncm_produto = db.Column(db.Text)
    origem_produto = db.Column(db.Text)
    codigo_barra_produto = db.Column(db.Text)
    codigo_barras_internos = db.Column(db.Text)
    obs_produto = db.Column(db.Text)
    tipo_produto = db.Column(db.Text)
    tamanho_produto = db.Column(db.Text)
    localizacao_produto = db.Column(db.Text)
    kit_produto = db.Column(db.Text)
    baixar_kit = db.Column(db.Text)
    desmembrar_kit = db.Column(db.Text)
    loja_visivel = db.Column(db.Text)
    loja_video_url = db.Column(db.Text)
    valor_tributos = db.Column(db.Text)
    valor_tributosEst = db.Column(db.Text)
    status_produto = db.Column(db.Text)
    id_comissionamento = db.Column(db.Text)
    id_regra_comissionamento_servico = db.Column(db.Text)
    data_cad_produto = db.Column(db.Text)
    data_mod_produto = db.Column(db.Text)
    data_mod_estoque = db.Column(db.Text)
    lixeira = db.Column(db.Text)
    endereco_fixo = db.Column(db.Text)
    controla_lote = db.Column(db.Text)
    controla_validade = db.Column(db.Text)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
