# trunk-ignore-all(black)
from datetime import datetime

from flask_sqlalchemy import SQLAlchemy

# from sqlalchemy import Index

db = SQLAlchemy()


class CC_REPORT(db.Model):
    ID = db.Column(db.String(255), primary_key=True, unique=True)
    ID_SEED = db.Column(db.String(512))
    ID_CC = db.Column(db.String(255))
    CC = db.Column(db.String(255))
    CC_LABEL = db.Column(db.String(255))
    VENCIMENTO = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    FORNECEDOR = db.Column(db.String(255))
    NOME_DESPESA = db.Column(db.String(255))
    SITUACAO = db.Column(db.String(255))
    DATA_PAGAMENTO = db.Column(db.DateTime, default=datetime.utcnow)
    CATEGORIA = db.Column(db.String(255))
    VALOR = db.Column(db.Float)
    TYPE = db.Column(db.String(32))
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class Relatorio_CC(db.Model):
    ID = db.Column(db.String(255), primary_key=True, unique=True)
    ID_SEED = db.Column(db.String(512))
    ID_CC = db.Column(db.String(255))
    CC = db.Column(db.String(255))
    CC_LABEL = db.Column(db.String(255))
    VENCIMENTO = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    FORNECEDOR = db.Column(db.String(255))
    NOME_DESPESA = db.Column(db.String(255))
    SITUACAO = db.Column(db.String(255))
    DATA_PAGAMENTO = db.Column(db.DateTime, default=datetime.utcnow)
    CATEGORIA = db.Column(db.String(255))
    VALOR = db.Column(db.Float)
    TYPE = db.Column(db.String(32))
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class DespesasRecorrentes(db.Model):
    id_custo = db.Column(db.Text, primary_key=True)
    id_empresa = db.Column(db.Text, nullable=False)
    nome_conta = db.Column(db.Text, nullable=False)
    id_categoria = db.Column(db.Text)
    categoria_custo = db.Column(db.Text)
    id_banco = db.Column(db.Text)
    id_fornecedor = db.Column(db.Text)
    nome_fornecedor = db.Column(db.Text)
    vencimento_custo = db.Column(db.Text)
    valor_custo = db.Column(db.Text)
    observacoes_custo = db.Column(db.Text)
    id_centro_custos = db.Column(db.Text)
    status_custo = db.Column(db.Text)
    forma_pagamento = db.Column(db.Text)
    periodicidade = db.Column(db.Text)
    dia_semana_ocorrencia = db.Column(db.Text)
    dia_mes_ocorrencia = db.Column(db.Text)
    intervalo_dias_ocorrencia = db.Column(db.Text)
    data_inicio_ocorrencia = db.Column(
        db.DateTime,  default=datetime.utcnow
    )
    data_fim_ocorrencia = db.Column(
        db.DateTime,  default=datetime.utcnow
    )
    data_cad_custo = db.Column(
        db.DateTime, default=datetime.utcnow
    )
    lixeira = db.Column(db.String(16))
    # created_at = db.Column(db.DateTime,  default=datetime.utcnow)
    # updated_at = db.Column(db.DateTime,  default=datetime.utcnow)

class Client_by_CC(db.Model):
    __tablename__ = "client_by_cc"
    CC = db.Column(db.Text, primary_key=True)
    id_cc = db.Column(db.Text)
    id_cliente = db.Column(db.Text)
    ref_cc = db.Column(db.Text)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class Update_cc_report_status(db.Model):
    cc_id = db.Column(db.String(512), primary_key=True)
    entries_runned = db.Column(db.Integer)
    outputs_runned = db.Column(db.Integer)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class CentroCustos(db.Model):
    __tablename__ = "centro_custos"
    id_centro_custos = db.Column(db.Text, primary_key=True)
    ref_centro_custos = db.Column(db.Text, nullable=False)
    desc_centro_custos = db.Column(db.Text, nullable=False)
    status_centro_custos = db.Column(db.String(16))
    data_cad_centro = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    lixeira = db.Column(db.String(16))
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
# trunk-ignore(git-diff-check/error)


class Employers(db.Model):
    __tablename__ = "employers"
    vhsys_id = db.Column(db.Integer, primary_key=True)
    matricula = db.Column(db.Integer)
    nome = db.Column(db.Text)
    cargo =db.Column(db.Text)
    cbo = db.Column(db.Text)
    rg = db.Column(db.Text)
    cpf = db.Column(db.Text)
    data_nascimento = db.Column(db.DateTime)
    salario = db.Column(db.Float)
    data_adm = db.Column(db.DateTime)
    data_dem = db.Column(db.DateTime)
    status = db.Column(db.Text)
    data_cad = db.Column(db.DateTime)
    data_mod = db.Column(db.DateTime)
    depto =  db.Column(db.Text)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class EmployersData(db.Model):
    __tablename__ = "employersData"
    id_funcionario =  db.Column(db.Text, primary_key=True)
    nome_funcionario  = db.Column(db.Text)
    rg_funcionario = db.Column(db.Text)
    cpf_funcionario = db.Column(db.Text)
    matricula_funcionario = db.Column(db.Text)
    sexo_funcionario = db.Column(db.Text)
    local_nascimento_funcionario = db.Column(db.Text)
    orgao_emissor_rg = db.Column(db.Text)
    serie_ctps_funcionario = db.Column(db.Text)
    cep_funcionario = db.Column(db.Text)
    endereco_funcionario = db.Column(db.Text)
    numero_funcionario = db.Column(db.Text)
    bairro_funcionario = db.Column(db.Text)
    cidade_funcionario = db.Column(db.Text)
    uf_funcionario = db.Column(db.Text)
    complemento_funcionario = db.Column(db.Text)
    celular_funcionario = db.Column(db.Text)
    fone_funcionario = db.Column(db.Text)
    email_funcionario = db.Column(db.Text)
    nome_pai_funcionario = db.Column(db.Text)
    nome_mae_funcionario = db.Column(db.Text)
    observacoes_funcionario = db.Column(db.Text)
    pis_funcionario = db.Column(db.Text)
    ctps_funcionario = db.Column(db.Text)
    uf_ctps_funcionario = db.Column(db.Text)
    banco_funcionario = db.Column(db.Text)
    agencia_funcionario = db.Column(db.Text)
    conta_funcionario = db.Column(db.Text)
    cargo_funcionario = db.Column(db.Text)
    nome_cargo_funcionario = db.Column(db.Text)
    cbo_funcionario = db.Column(db.Text)
    departamento_funcionario = db.Column(db.Text)
    trabalho_inicio = db.Column(db.Text)
    trabalho_termino = db.Column(db.Text)
    intervalo_inicio = db.Column(db.Text)
    intervalo_termino = db.Column(db.Text)
    salario_funcionario = db.Column(db.Text)
    status_funcionario = db.Column(db.Text)
    data_admissao_funcionario = db.Column(db.DateTime)
    data_nascimento_funcionario = db.Column(db.DateTime)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    
class EmployersDataDependents(db.Model):
    __tablename__ = "employersDependents"
    dependents_id =  db.Column(db.Text, primary_key=True)
    id_funcionario = db.Column(db.Text)
    nome_funcionario = db.Column(db.Text)
    nome_dependente = db.Column(db.Text)
    tipo_dependente = db.Column(db.Text)
    fone_dependente = db.Column(db.Text)
    rg = db.Column(db.Text)
    cpf = db.Column(db.Text)
    data_nascimento = db.Column(db.DateTime)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class EmployersDataBenefits(db.Model):
    __tablename__ = "employersBenefits"
    benefit_id =  db.Column(db.Text, primary_key=True)
    id_funcionario = db.Column(db.Text, primary_key=True)
    nome_funcionario = db.Column(db.Text)
    nome = db.Column(db.Text)
    valor = db.Column(db.Float)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)



class Update_extension_services(db.Model):
    ACTION = db.Column(db.Text, primary_key=True)
    RUN_AFTER = db.Column(db.Integer, default =720)
    RUN_STATUS = db.Column(db.Integer, default =0)
    PROGRESS_VALUE = db.Column(db.Integer, default =0)
    LAST_RUN = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    LAST_UPDATE = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class SalesNFReport(db.Model):
    __tablename__ = "salesNFReport"
    ID = db.Column(db.Text)
    Nota = db.Column(db.Text , primary_key=True)
    Cliente = db.Column(db.Text)
    CNPJ = db.Column(db.Text)
    Endereco = db.Column(db.Text)
    Numero = db.Column(db.Text)
    Complemento = db.Column(db.Text)
    Bairro = db.Column(db.Text)
    Cidade = db.Column(db.Text)
    Estado = db.Column(db.Text)
    CEP = db.Column(db.Text)
    Email = db.Column(db.Text)
    Telefone = db.Column(db.Text)
    Vendedor = db.Column(db.Text)
    ValorProdutos = db.Column(db.Numeric(10, 2), default=0.00)
    ValorDesconto = db.Column(db.Numeric(10, 2), default=0.00)
    ValorFrete = db.Column(db.Text)
    ValorTotal = db.Column(db.Numeric(10, 2), default=0.00)
    TotalParcelas = db.Column(db.Text)
    TotalUnidades = db.Column(db.Text)
    ValorICMS = db.Column(db.Numeric(10, 2), default=0.00)
    ValorIPI = db.Column(db.Numeric(10, 2), default=0.00)
    ValorST = db.Column(db.Numeric(10, 2), default=0.00)
    PesoBruto = db.Column(db.Numeric(10, 2), default=0.00)
    PesoLiquido = db.Column(db.Numeric(10, 2), default=0.00)
    Transportadora = db.Column(db.Text)
    DataPedido = db.Column(db.Text)
    QtdeProdutos = db.Column(db.Text)
    CFOP = db.Column(db.Text)
    Natureza = db.Column(db.Text)
    Contas = db.Column(db.Text)
    Estoque = db.Column(db.Text)
    Comissao = db.Column(db.Text)
    Chave = db.Column(db.Text)
    Protocolo = db.Column(db.Text)
    DataEmissao = db.Column(db.Text)
    DataAutorizacao = db.Column(db.Text)
    Situacao = db.Column(db.Text)
    DataCad = db.Column(db.Text)
    DataMod = db.Column(db.Text)
    Observacoes = db.Column(db.Text)
    ObservacoesInternas = db.Column(db.Text)
    CategoriaFinanceira = db.Column(db.Text)
    Volumes = db.Column(db.Text)
    EmitidoPor = db.Column(db.Text)
    CanceladoPor = db.Column(db.Text)
    DataCancelamento = db.Column(db.Text)
    cc_ref = db.Column(db.Text)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


class ServiceNFReport(db.Model):
    __tablename__ = "serviceNFReport"
    ID = db.Column(db.Text)
    RPS = db.Column(db.Text, primary_key=True)
    Nota = db.Column(db.Text)
    Cliente = db.Column(db.Text)
    CNPJ = db.Column(db.Text)
    Endereco = db.Column(db.Text)
    Numero = db.Column(db.Text)
    Complemento = db.Column(db.Text)
    Bairro = db.Column(db.Text)
    Cidade = db.Column(db.Text)
    Estado = db.Column(db.Text)
    CEP = db.Column(db.Text)
    Email = db.Column(db.Text)
    Telefone = db.Column(db.Text)
    Vendedor = db.Column(db.Text)
    ValorServicos = db.Column(db.Numeric(10, 2), default=0.00)
    ValorTotal = db.Column(db.Numeric(10, 2), default=0.00)
    TotalParcelas = db.Column(db.Text)
    ValorDeducoes = db.Column(db.Text)
    Aliquota = db.Column(db.Text)
    ValorISS = db.Column(db.Numeric(10, 2), default=0.00)
    ISSRetido = db.Column(db.Text)
    ValorCOFINS = db.Column(db.Numeric(10, 2), default=0.00)
    ValorPIS = db.Column(db.Numeric(10, 2), default=0.00)
    ValorCSLL = db.Column(db.Numeric(10, 2), default=0.00)
    ValorIR = db.Column(db.Numeric(10, 2), default=0.00)
    ValorINSS = db.Column(db.Numeric(10, 2), default=0.00)
    ValorTributos = db.Column(db.Numeric(10, 2), default=0.00)
    DataPedido = db.Column(db.Text)
    LocalPrestacao = db.Column(db.Text)
    Contas = db.Column(db.Text)
    Chave = db.Column(db.Text)
    Protocolo = db.Column(db.Text)
    Descricao = db.Column(db.Text)
    DataEmissao = db.Column(db.Text)
    Situacao = db.Column(db.Text)
    DataCad = db.Column(db.Text)
    DataMod = db.Column(db.Text)
    cc_ref = db.Column(db.Text)
    ObservacoesInternas = db.Column(db.Text)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)



class NF_ServiceMetadata(db.Model):
    codigo = db.Column(db.Text, primary_key=True)
    contas =db.Column(db.Text)
    boletos = db.Column(db.Text)
    nota = db.Column(db.Text)
    cliente = db.Column(db.Text)
    status = db.Column(db.Text)
    vendedor = db.Column(db.Text)
    chave = db.Column(db.Text)
    numeronfs = db.Column(db.Text)
    notarecibo = db.Column(db.Text)
    vinculooscomnfs = db.Column(db.Text)
    runned = db.Column(db.Text)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

class NF_Service(db.Model):
    id_servico = db.Column(db.Text, primary_key=True)
    obs_interno_pedido =db.Column(db.Text)
    obs_pedido = db.Column(db.Text)
    numero_processo = db.Column(db.Text)
    condicao_pagamento = db.Column(db.Text)
    condicao_pagamento_id = db.Column(db.Text)
    valor_iss = db.Column(db.Text)
    aliq_iss = db.Column(db.Text)
    valor_ir = db.Column(db.Text)
    aliq_ir = db.Column(db.Text)
    valor_contribuicao = db.Column(db.Text)
    aliq_contribuicao = db.Column(db.Text)
    valor_pis = db.Column(db.Text)
    aliq_pis = db.Column(db.Text)
    valor_cofins = db.Column(db.Text)
    aliq_cofins = db.Column(db.Text)
    valor_material = db.Column(db.Text)
    valor_tributos_mun = db.Column(db.Text)
    valor_aliq_tributos_mun = db.Column(db.Text)
    valor_tributos = db.Column(db.Text)
    valor_aliq_tributos = db.Column(db.Text)
    valor_imposto = db.Column(db.Text)
    valor_aliquota = db.Column(db.Text)
    valor_base_calculo = db.Column(db.Text)
    valor_condicionado = db.Column(db.Text)
    valor_incondicionado = db.Column(db.Text)
    valor_deducoes = db.Column(db.Text)
    itemLista_servico = db.Column(db.Text)
    valor_total_nota = db.Column(db.Text)
    valor_total_servicos = db.Column(db.Text)
    desc_servicos = db.Column(db.Text)
    serie_nota = db.Column(db.Text)
    id_pedido = db.Column(db.Text)
    vendedor_pedido_id = db.Column(db.Text)
    vendedor_pedido = db.Column(db.Text)
    ultrapassar_limite_credito = db.Column(db.Text)
    contas_pedido = db.Column(db.Text)
    id_cliente = db.Column(db.Text)
    nome_cliente = db.Column(db.Text)
    cc_ref = db.Column(db.Text)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

class Tangerino_entries(db.Model):
    ID = db.Column(db.Text, primary_key=True)
    DAY_REF = db.Column(db.Text)
    DAY = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    EMPLOYER = db.Column(db.Text)
    EMPLOYER_CPF = db.Column(db.Text)
    worked_hours = db.Column(db.Text)
    worked_hours_minutes = db.Column(db.Integer)
    work_expect = db.Column(db.Text)
    work_expect_minutes = db.Column(db.Integer)
    TURN_01_START = db.Column(db.DateTime, default=datetime.utcnow)
    TURN_01_END = db.Column(db.DateTime,  default=datetime.utcnow)
    TURN_02_START = db.Column(db.DateTime,  default=datetime.utcnow)
    TURN_02_END = db.Column(db.DateTime,  default=datetime.utcnow)
    TURN_03_START = db.Column(db.DateTime,  default=datetime.utcnow)
    TURN_03_END = db.Column(db.DateTime, default=datetime.utcnow)
    TURN_04_START = db.Column(db.DateTime,  default=datetime.utcnow)
    TURN_04_END = db.Column(db.DateTime,  default=datetime.utcnow)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime,  default=datetime.utcnow)


class Valor_base_by_employer(db.Model):
    id_matricula = db.Column(db.Integer, primary_key=True)
    employer = db.Column(db.String(512), unique=True)
    valor_base = db.Column(db.Float)
    adm_percent = db.Column(db.Float)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)




class ExensionExecutionManager(db.Model):
    __tablename__ = "extensionExecutionManager"
    table_ref = db.Column(db.Text, primary_key=True)
    running = db.Column(db.Text)  # Running, Done, Error
    run_interval = db.Column(db.Integer)  # In hours
    service_ref = db.Column(db.Text)
    last_run = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)